/* eslint-disable import/no-anonymous-default-export */

import {
  API_API_MANAGEMENT,
  API_AUTH,
  API_BRANCH,
  API_CONFIG_COLOR,
  API_CUSTOMER,
  API_DEPARTMENT,
  API_FORM_MANAGEMENT,
  API_FORM_SIGN_MANAGEMENT,
  API_FORM_SIGN_MONITOR,
  API_LC_ONLINE,
  API_LC_ONLINE_CUSTOMER,
  API_MANAGEMENT_FEE,
  API_MENU,
  API_PER,
  API_PROCESS,
  API_PROCESS_TRACKING,
  API_REPORT_MANAGEMENT,
  API_ROLES,
  API_SECURITY,
  API_SYS_ACCESS,
  API_USER,
  API_MONEY_TYPE,
  API_RECEVING_INTEREST,
  API_RECEIVING_INTEREST,
  API_PERIOD,
  API_TERM_DEPOSIT_PRODUCT,
  APT_MANAGEMENT_API,
  API_FEE_GROUP,
  API_NOTIFICATION,
} from "./CommandURL";
import {FORM_SERVICE} from "./proxy";

// const URL_SERVICE_LIVE = Config.API_URL + Config.API_PATH;

export default {
  API_IMAGE: "http://10.86.144.195:8905",
  LOGIN: API_AUTH + "login",
  API_GET_PERMISSION: API_SECURITY + "getPermission",
  API_LOGIN: API_SECURITY + "login",
  API_LOGOUT: API_AUTH + "logOut",

  //USER
  CREATE_USER: API_USER + "createUser",
  UPDATE_USER: API_USER + "updateUser",
  GET_USER_PAGING: API_USER + "getUserPaging",
  SEARCH_USER_COMPACT: API_USER + "searchUserCompacts",

  // Branch
  GET_LIST_BRANCH_PARENT: API_BRANCH + "listBranchParent",
  GET_LIST_BRANCH: API_BRANCH + "filterBranch",
  CREATE_BRANCH: API_BRANCH + "create",
  UPDATE_BRANCH: API_BRANCH + "update",

  //Menu
  GET_LIST_MENU: API_MENU + "findMenuByUserId",
  CREATE_MENU: API_MENU + "create",
  GET_MENU_BY_CONDITION: API_MENU + "getByCondition",
  UPDATE_MENU: API_MENU + "update",
  FIND_ALL_MENU: API_MENU + "findAllMenu",
  FIND_MENU_BY_USERID: API_MENU + "findMenuByUserId",

  // Roles
  GET_ROLE_BY_CONDITION: API_ROLES + "getByCondition",
  CREATE_ROLE: API_ROLES + "create",
  UPDATE_ROLE: API_ROLES + "update",

  // Process
  GET_LIST_PROCESS: API_PROCESS + "findByCondition",
  FETCH_PROCESS: API_PROCESS + "fetchProcess",
  FIND_STEPS_BY_PROCESS_ID: API_PROCESS + "findStepByProcessId",
  INSERT_PROCESS: API_PROCESS + "insert",
  UPDATE_CONFIG_STEP: API_PROCESS + "updateStepConfig",
  ASSIGN_PROCESS_TO_TRANSFER_TYPE: API_PROCESS + "assignToProcess",

  //Process Tracking
  GET_PROCESS_DETAILS: API_PROCESS_TRACKING + "getProcessTrackingDetail",

  // Permission
  GET_PERMISSION: API_PER + "fetchPermissionByUserIdAndURL",
  GET_CONDITION_BY_PERMISSION: API_PER + "getByCondition",
  SAVE_PERMISSION: API_PER + "savePermission",

  // Department
  FIND_ALL: API_DEPARTMENT + "getAll",
  GET_DEPARTMENT_PAGING: API_DEPARTMENT + "getDepartmentPaging",
  CREATE_DEPARTMENT: API_DEPARTMENT + "createDepartment",
  UPDATE_DEPARTMENT: API_DEPARTMENT + "updateDepartment",
  DELETE_DEPARTMENT: API_DEPARTMENT + "deleteDepartment",
  EXPORT_DEPARTMENT: API_DEPARTMENT + "exportDepartment",
  IMPORT_DEPARTMENT: API_DEPARTMENT + "importDepartment",
  EXPORT_TEMPLATE_DEPARTMENT: API_DEPARTMENT + "exportTemplate",
  FIND_DEPARTMENT_CHART: API_DEPARTMENT + "findDepartmentChart",
  GET_DEPARTMENT_PARENT_PAGING: API_DEPARTMENT + "getDepartmentParentPaging",
  EXPORT_TEMPLATE_DEPARTMENT_PARENT:
    API_DEPARTMENT + "exportTemplateDepartmentParent",
  EXPORT_DEPARTMENT_PARENT: API_DEPARTMENT + "exportDepartmentParent",
  IMPORT_DEPARTMENT_PARENT: API_DEPARTMENT + "importDepartmentParent",
  FIND_DEPARTMENT_INVENTORY: API_DEPARTMENT + "findDepartmentInventory",
  GET_STEPS_BY_PROCESS_ID: API_PROCESS + "findStepByProcessId",

  // Fee
  SEARCH_BY_FEE: API_MANAGEMENT_FEE + "search",
  CHECK_TRAN: API_MANAGEMENT_FEE + "checkTran",
  PROCESS_FEE: API_MANAGEMENT_FEE + "appFee/process",
  FIND_SYS_CCY_ALL: API_MANAGEMENT_FEE + "findSysCCYAll",
  ADD_TRAN_CODE_FEE: API_MANAGEMENT_FEE + "tranCodeFee/add",
  UPDATE_TRAN_CODE_FEE: API_MANAGEMENT_FEE + "tranCodeFee/update",
  SEARCH_TRAN_CODE_FEE: API_MANAGEMENT_FEE + "tranCodeFee/search",

  // system access
  GET_SYS_ACCESS: API_SYS_ACCESS + "findUserLoginLog",
  EXPORT_USER_LOGIN: API_SYS_ACCESS + "exportUserLoginLogForReport",

  //Customer
  CREATE_CUSTOMER: API_CUSTOMER + "create",
  UPDATE_CUSTOMER: API_CUSTOMER + "update",
  EXPORT_CUSTOMER: API_CUSTOMER + "export",
  GET_CUSTOMER: API_CUSTOMER + "getCustomer",
  GET_LOGIN_SESSION: API_SYS_ACCESS + "getLoginSession",

  //LC ONLINE
  GET_LC_ONLINE_DETAIL: API_LC_ONLINE + "getCreateLconline",
  GET_LC_ONLINE_APPROVE: API_LC_ONLINE + "actionTicket",
  GET_LC_ONLINE_APPROVE_V2: API_LC_ONLINE + "actionTicketV2",
  ACTION_LC_TICKET: API_LC_ONLINE + "actionTicket",
  // http://10.86.144.142:8122/api/portal/lcOnline/exportLCOnline
  EXPORT_MT700V1: API_LC_ONLINE + "exportMT700",
  EXPORT_LC_ONLINE: API_LC_ONLINE + "exportLCOnline",
  EXPORT_LCMT700_BYCUSTOMER: API_LC_ONLINE + "exportMT700ByCustomer",
  //   api/portal/managementFee/checkFeeAndTranCode
  CALL_CHARGES_FEE: API_MANAGEMENT_FEE + "checkFeeAndTranCode",

  // LC Online
  GET_CUSTOMER_INFO: API_CUSTOMER + "getCustomerByCifCode",
  GET_BALANCE_CUSTOMER: API_LC_ONLINE + "getBalances",
  GET_CORE_ACCOUNT_INQUIRY_CUSTOMER: API_LC_ONLINE + "coreAccountInquiry",
  GET_CORE_INFO_ACCOUNT: API_LC_ONLINE + "getInfoAccount",

  NVTTT_CREATE_LC_CONTRACT: API_LC_ONLINE + "createLcOnlineV2",
  GET_ALL_CODE_LCONLINE: API_LC_ONLINE + "getAllCodeLcOnline",
  DOWNLOAD_FILE_LCONLINE: API_LC_ONLINE + "downloadFileLcOnline",
  //LC CUSTOMER
  GET_ALL_BRANCH: API_LC_ONLINE_CUSTOMER + "findAllLCBranch",
  GET_ALL_SWIFT: API_LC_ONLINE_CUSTOMER + "findAllSwift",
  GET_LIST_ACCOUNTS_BY_CUSTOMER:
    API_LC_ONLINE_CUSTOMER + "getListAccountsByCustomer",
  CREATE_LC_CONTRACT: API_LC_ONLINE_CUSTOMER + "lcCreateContract",

  // CREATE_REPORT: API_REPORT_MANAGEMENT + "createReport",
  // UPDATE_REPORT: API_REPORT_MANAGEMENT + "updateReport",
  // GET_REPORT_MANAGEMENT_BY_CONDITION:
  //   API_REPORT_MANAGEMENT + "getReportManagementByCondition",
  // http://10.86.144.142:8122/api/portal/lcOnline/exportLCOnline

  //config colorf
  GET_LIST_CONFIG_COLOR: API_CONFIG_COLOR + "searchConfigColor",
  CREATE_CONFIG_COLOR: API_CONFIG_COLOR + "createConfigColor",
  UPDATE_CONFIG_COLOR: API_CONFIG_COLOR + "updateConfigColor",
  //lc online
  GET_LC_ONLINE: API_LC_ONLINE + "getAllLconline",
  EXPORT_M700: API_LC_ONLINE + "exportMT700",

  // API Management
  CREATE_API_REQUEST: API_API_MANAGEMENT + "createRequestAPI",
  UPDATE_API_REQUEST: API_API_MANAGEMENT + "updateRequestAPI",
  DELETE_API_REQUEST: API_API_MANAGEMENT + "deleteRequestAPI",
  PAGING_API_REQUEST: API_API_MANAGEMENT + "getPaging",
  MAKE_API_REQUEST: API_API_MANAGEMENT + "makeRequest",

  // form
  GET_FORM_MANAGEMENT: API_FORM_MANAGEMENT + "getPaging",
  CREATE_FORM: API_FORM_MANAGEMENT + "create",
  UPDATE_FORM: API_FORM_MANAGEMENT + "update",
  GET_FORM_BY_USE_AT: API_FORM_MANAGEMENT + "getByUseAt",

  // form sign
  GET_FORM_SIGN: API_FORM_SIGN_MANAGEMENT + "search",
  FETCH_SIGN_FORM_BY_MONITOR_CODE:
    API_FORM_SIGN_MANAGEMENT + "fetchByMonitorCode",
  FETCH_SIGN_FORM_BY_TELLER_APP: API_FORM_SIGN_MANAGEMENT + "fetchByTellerApp",
  SIGN_FORM: API_FORM_SIGN_MANAGEMENT + "createFormSign",
  RE_SUBMIT_FORM: API_FORM_SIGN_MANAGEMENT + "resubmitFormSign",
  APPROVE_SIGN_FORM: API_FORM_SIGN_MANAGEMENT + "approveFormSign",
  RETURN_SIGN_FORM: API_FORM_SIGN_MANAGEMENT + "returnFormSign",
  RETURN_SIGN_FORM_TO_CREATOR:
    API_FORM_SIGN_MANAGEMENT + "returnFormSignToCreator",
  REJECT_SIGN_FORM: API_FORM_SIGN_MANAGEMENT + "rejectFormSign",

  // Form Monitor
  SIGN_FORM_MONITOR_LIST: API_FORM_SIGN_MONITOR + "search",
  SIGN_FORM_MONITOR: API_FORM_SIGN_MONITOR + "create",
  MONITOR_FORM_BY_USE_AT: API_FORM_SIGN_MONITOR + "getByUseA",

  // Report
  CREATE_REPORT: API_REPORT_MANAGEMENT + "createReport",
  UPDATE_REPORT: API_REPORT_MANAGEMENT + "updateReport",
  GET_REPORT_MANAGEMENT_BY_CONDITION:
    API_REPORT_MANAGEMENT + "getReportManagementByCondition",
  EXPORT_REPORT: API_REPORT_MANAGEMENT + "export",
  EXPORT_REPORT_UPDATE: API_REPORT_MANAGEMENT + "exportForUpdate",
  EXPORT_REPORT_UPDATE_VALUE: API_REPORT_MANAGEMENT + "exportUpdateValue",
  GET_PARAM_BY_REPORT:
    API_REPORT_MANAGEMENT + "getParamByTemplate",

  //Noti
  GET_NOTIFICATION : API_NOTIFICATION+"getNotiSys",
  UPDATE_VIEW_NOTIFICATION : API_NOTIFICATION+"updateNotiSys",

  // money type
  GET_MONEY_TYPE: API_MONEY_TYPE + "getMoneyType",
  CREATE_MONEY_TYPE: API_MONEY_TYPE + "createMoneyType",
  UPDATE_MONEY_TYPE: API_MONEY_TYPE + "updateMoneyType",

  // Receiving Interest
  GET_RECEIVING_INTEREST_BY_CONDITION:
    API_RECEIVING_INTEREST + "getByCondition",
  CREATE_RECEIVING_INTEREST: API_RECEIVING_INTEREST + "create",
  UPDATE_RECEIVING_INTEREST: API_RECEIVING_INTEREST + "update",

  // period
  GET_PERIOD: API_PERIOD + "getPeriod",
  CREATE_PERIOD: API_PERIOD + "createPeriod",
  UPDATE_PERIOD: API_PERIOD + "updatePeriod",
  //TERM DEPOSIT PRODUCT
  GET_TERM_DEPOSIT_PRODUCT_BY_CONDITION:
    API_TERM_DEPOSIT_PRODUCT + "getByCondition",
  CREATE_TERM_DEPOSIT_PRODUCT: API_TERM_DEPOSIT_PRODUCT + "create",
  UPDATE_TERM_DEPOSIT_PRODUCT: API_TERM_DEPOSIT_PRODUCT + "update",

  API_MANAGEMENT_PAGING: APT_MANAGEMENT_API + "getPaging",

  // fee group
  GET_FEE_GROUP: API_FEE_GROUP + "getByCondition",
  CREATE_FEE_GROUP: API_FEE_GROUP + "create",
  UPDATE_FEE_GROUP: API_FEE_GROUP + "update",

  // Form field config
  UPDATE_MULTI_FORM_FIELD_CONFIG: FORM_SERVICE + 'form-field-config/updateMultiFieldConfig'
};
